### ISSUE TITLE
I'm getting errors trying to import this in ng2 4.X

### ISSUE THREAD

**Issue by grimace** [hyperwidget/ng2-group-multiselect#4]
import { MultiSelectComponent } from "./raw-multiselect.component.ts";

the error says that import should not end with '.ts'

also:

Unexpected directive 'MultiSelectComponent' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by hyperwidget** [comment]
Awesome; thanks!

**Comment by hyperwidget** [comment]
@grimace Everything's been updated to work with Ng4 - if any issues, please see the demo & updated readme.

Thanks for making the issue :D
